Name : Naveen Rajendran

NUID : 001304569

Assignment 1

In [1]:
import numpy
x = [1,2,3]
numpy_array = numpy.array(x)
print("Python Array:",x)
print("Numpy Array:",numpy_array)

Python Array: [1, 2, 3]
Numpy Array: [1 2 3]


In [2]:
rows, cols = (3, 2)
# method 2a
arr = [[6]*cols]*rows
 
for row in arr:
    print(row)

[6, 6]
[6, 6]
[6, 6]


In [3]:
import numpy
arr = []
for i in range(2,102,2):
    arr.append(i)

print ("Array Elements:",arr)

print ("Array Mean Value:",numpy.mean(arr))

Array Elements: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
Array Mean Value: 51.0


In [4]:
import numpy as np
x = np.random.random((3, 3, 3))
print("Maximum Value:", np.amax(x))
print("Minimum Value:", np.amin(x))


Maximum Value: 0.9236517577350074
Minimum Value: 0.0005832885983895197


In [5]:
import numpy as np
arr = np.arange(10,22).reshape((3, 4))
print(arr)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [6]:
import numpy as np
arr = np.arange(10)
arr = np.arange(5,len(arr)*3+3, 3)
print(arr)

[ 5  8 11 14 17 20 23 26 29 32]


In [7]:
import numpy as np
x = np.random.random((10,10))
print("Size of 10 x 10 Array:",x.size * x.itemsize)

Size of 10 x 10 Array: 800


In [8]:
import numpy as np
num =np.array([int(x==4) for x in range(10)])
print(num)

[0 0 0 0 1 0 0 0 0 0]


In [9]:
import numpy as np
arr = np.arange(10,50, 1)
print("Original Arr: \n",arr)
arr = np.flipud(arr)
print("Reversed Arr: \n",arr)

Original Arr: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Reversed Arr: 
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [10]:
import numpy as np
x = np.random.seed(0)
x = np.random.random((3,2))
print(x)

[[0.5488135  0.71518937]
 [0.60276338 0.54488318]
 [0.4236548  0.64589411]]


In [11]:
import numpy as np
x = np.ones((10,10))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [12]:
import numpy as np
x = np.array([[1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1]])
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)


[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


In [13]:
import numpy as np

x = np.array([[1, 2, 3, 4, 5]])
d = np.diag(x[0])
print('The diagonal: ')
print(d)
print('Diagonal 1 place shift lower:')
dl = np.diag(x[0],k=-1)
print(dl)

The diagonal: 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
Diagonal 1 place shift lower:
[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


In [14]:
import numpy as np
x = np.zeros((5,5))
x += np.arange(5)
print(x)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [15]:
import numpy as np
x = np.random.random((10))
print(np.sort(x))

[0.07103606 0.0871293  0.38344152 0.43758721 0.52889492 0.56804456
 0.79172504 0.891773   0.92559664 0.96366276]


In [16]:
x = [1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2]
count = 0
for i in range(len(x)-1):
    if ( x[i] == 1):
        count = count + 1
        if (count == 5):
            break
print("5th occurence at index",i)



5th occurence at index 8


In [17]:
import numpy as np
arr = np.arange(1,11)
arr = np.array_split(arr,3)

print(arr)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


In [18]:
import numpy as np
arr = np.arange(0,16).reshape((4, 4))
arr = np.hsplit(arr,2)
print(arr)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [19]:
import numpy as np
arr = np.array([[5,10,15],[20,25,30],[35,40,45]])

print(arr[0:2,1:3])

print("\n",arr[1:2,0:1])


[[10 15]
 [25 30]]

 [[20]]


In [20]:
import numpy as np
x = np.array([[ 1,2,3],[ 4,5,6]])
y = np.array([[ 7,8,9],[10,11,12]])

arr = np.concatenate((x,y), axis=1)

print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [21]:
import numpy as np
arr = np.arange(10,22).reshape((3,4))
print(arr)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [22]:
import numpy as np
arr = np.random.randint(low=1,high=10,size=(5,3))
print("Generated Array:\n",arr)
print("Min/Max:\n",np.round(np.min(arr, axis=1)/np.max(arr, axis=1),2))


Generated Array:
 [[4 1 4]
 [6 1 3]
 [4 9 2]
 [4 4 4]
 [8 1 2]]
Min/Max:
 [0.25 0.17 0.22 1.   0.12]


In [23]:
import numpy as np
arr = np.random.random((5,5))
print ("Randomized Matrix: \n",x)
arr_max,arr_min = arr.max(), arr.min()
arr = (arr - arr_min)/(arr_max - arr_min)
print("After Normalization \n")
print(arr)

Randomized Matrix: 
 [[1 2 3]
 [4 5 6]]
After Normalization 

[[0.13453537 1.         0.54333067 0.42756353 0.2654405 ]
 [0.81592065 0.47237325 0.59364569 0.         0.64678605]
 [0.64080279 0.64602839 0.99900544 0.71610914 0.36799415]
 [0.45172436 0.73318577 0.04475279 0.69985045 0.70403151]
 [0.20693064 0.11895343 0.32038583 0.37253348 0.59554964]]


In [24]:
import numpy as np
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

arr123=np.concatenate((arr1, arr2, arr3), axis=None)

print(arr123)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
import numpy as np
arr = np.random.seed(0)
arr = np.random.randint(low=0,high=100,size=(1,20))
print("Original Array \n",arr)
aa = arr [(arr >= 15) * (arr <= 55)]
print("Resultant Array With Range of 15 to 55 \n", aa)

Original Array 
 [[44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]]
Resultant Array With Range of 15 to 55 
 [44 47 21 36 39 46]


In [26]:
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

result = np.where(a == b)

print(result)


(array([1, 3, 5, 7], dtype=int64),)


In [27]:
import numpy as np
arr = np.arange(0,21)
print("Original Array \n",arr)
odd_val = (arr%2 == 1) 
arr[odd_val] = -1 
print("Modified Array with odd values = -1 \n",arr)

Original Array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Modified Array with odd values = -1 
 [ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20]


In [28]:
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
%timeit -n 10 np.add(a,b)

797 ns ± 552 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [29]:
import numpy as np
arr = np.zeros((10,10))
np.put(arr,[0,1,2],[11,22,33])
print("\n Inserting three values inside zeros array with np.put \n",arr)


 Inserting three values inside zeros array with np.put 
 [[11. 22. 33.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [30]:
import numpy as np
arr = np.random.random((5,10))
print("\n Generated 5 x 10 array: \n", arr)
arr = arr - arr.mean(axis=1, keepdims=True)
print("\n Mean Subtracted Array: \n",arr)


 Generated 5 x 10 array: 
 [[0.3927848  0.83607876 0.33739616 0.64817187 0.36824154 0.95715516
  0.14035078 0.87008726 0.47360805 0.80091075]
 [0.52047748 0.67887953 0.72063265 0.58201979 0.53737323 0.75861562
  0.10590761 0.47360042 0.18633234 0.73691818]
 [0.21655035 0.13521817 0.32414101 0.14967487 0.22232139 0.38648898
  0.90259848 0.44994999 0.61306346 0.90234858]
 [0.09928035 0.96980907 0.65314004 0.17090959 0.35815217 0.75068614
  0.60783067 0.32504723 0.03842543 0.63427406]
 [0.95894927 0.65279032 0.63505887 0.99529957 0.58185033 0.41436859
  0.4746975  0.6235101  0.33800761 0.67475232]]

 Mean Subtracted Array: 
 [[-1.89693717e-01  2.53600251e-01 -2.45082352e-01  6.56933594e-02
  -2.14236973e-01  3.74676646e-01 -4.42127732e-01  2.87608746e-01
  -1.08870467e-01  2.18432239e-01]
 [-9.59820617e-03  1.48803844e-01  1.90556969e-01  5.19441064e-02
   7.29754373e-03  2.28539939e-01 -4.24168079e-01 -5.64752664e-02
  -3.43743342e-01  2.06842491e-01]
 [-2.13685173e-01 -2.95017354e-01 -

In [31]:
arr = [3,6,9,25,10,8]
print("To get all elements except first", arr[1:])
print("To get all elements except last", arr[:-1])
print("Get every element of the array",arr[:len(arr)])
print("Reverse Array",list(reversed(arr)))


To get all elements except first [6, 9, 25, 10, 8]
To get all elements except last [3, 6, 9, 25, 10]
Get every element of the array [3, 6, 9, 25, 10, 8]
Reverse Array [8, 10, 25, 9, 6, 3]


In [32]:
import numpy as np
arr = np.arange(0,32).reshape((8,4))
print("\n Randomized Array \n",arr)
np.put(arr,3,0)
print("\n 3rd element set to zero \n",arr)
print("\n 2nd column \n",arr[1,:])
print("\n 3 x 3 Region \n",arr[0:3,0:3])



 Randomized Array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

 3rd element set to zero 
 [[ 0  1  2  0]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

 2nd column 
 [4 5 6 7]

 3 x 3 Region 
 [[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [33]:
import numpy as np
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [34]:
import numpy as np
a_2d = [[3,3,3],[4,4,4],[5,5,5]]
x = np.array(a_2d)
b_1d = [1,2,3]
y = np.array(b_1d).reshape(3,1)
result = np.subtract(x,y)
print("\nSubtracted Array\n ",result)


Subtracted Array
  [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [35]:
from numpy import array
a = array([[ 1, 2, 3, 4, 5, 6],
            [1, 2, 3, 4, 5, 6],
            [1, 2, 3, 4, 5, 6],
            [1, 2, 3, 4, 5, 6],
            [1, 2, 3, 4, 5, 6],
            [1, 2, 3, 4, 5, 6]])
b = array([1,2,3,4,5,6]).reshape((6,1))

print("Multiplication via Numpy Broadcasting \n",a*b)

print("\n Multiplication Table By Nested Loop Method")

for j in range(1,7):
    for k in range(1,7):
        print(j*k , end ="\t")
    print("\n")

Multiplication via Numpy Broadcasting 
 [[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]

 Multiplication Table By Nested Loop Method
1	2	3	4	5	6	

2	4	6	8	10	12	

3	6	9	12	15	18	

4	8	12	16	20	24	

5	10	15	20	25	30	

6	12	18	24	30	36	

